package nodomain.freeyourgadget.gadgetbridge.entities;

import de.greenrobot.dao.AbstractDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEVICE_ATTRIBUTES".
 */
public class DeviceAttributes implements nodomain.freeyourgadget.vimo.model.ValidByDate {

    private Long id;
    /** Not-null value. */
    private String firmwareVersion1;
    private String firmwareVersion2;
    private java.util.Date validFromUTC;
    private java.util.Date validToUTC;
    private long deviceId;
    private String volatileIdentifier;

    public DeviceAttributes() {
    }

    public DeviceAttributes(Long id) {
        this.id = id;
    }

    public DeviceAttributes(Long id, String firmwareVersion1, String firmwareVersion2, java.util.Date validFromUTC, java.util.Date validToUTC, long deviceId, String volatileIdentifier) {
        this.id = id;
        this.firmwareVersion1 = firmwareVersion1;
        this.firmwareVersion2 = firmwareVersion2;
        this.validFromUTC = validFromUTC;
        this.validToUTC = validToUTC;
        this.deviceId = deviceId;
        this.volatileIdentifier = volatileIdentifier;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirmwareVersion1() {
        return firmwareVersion1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirmwareVersion1(String firmwareVersion1) {
        this.firmwareVersion1 = firmwareVersion1;
    }

    public String getFirmwareVersion2() {
        return firmwareVersion2;
    }

    public void setFirmwareVersion2(String firmwareVersion2) {
        this.firmwareVersion2 = firmwareVersion2;
    }

    @Override
    public java.util.Date getValidFromUTC() {
        return validFromUTC;
    }

    public void setValidFromUTC(java.util.Date validFromUTC) {
        this.validFromUTC = validFromUTC;
    }

    @Override
    public java.util.Date getValidToUTC() {
        return validToUTC;
    }

    public void setValidToUTC(java.util.Date validToUTC) {
        this.validToUTC = validToUTC;
    }

    public long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(long deviceId) {
        this.deviceId = deviceId;
    }

    public String getVolatileIdentifier() {
        return volatileIdentifier;
    }

    public void setVolatileIdentifier(String volatileIdentifier) {
        this.volatileIdentifier = volatileIdentifier;
    }

}
