package nodomain.freeyourgadget.gadgetbridge.entities;
import android.os.Build;
import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import nodomain.freeyourgadget.gadgetbridge.entities.HPlusHealthActivityOverlay;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HPLUS_HEALTH_ACTIVITY_OVERLAY".
*/
public class HPlusHealthActivityOverlayDao extends AbstractDao<HPlusHealthActivityOverlay, Void> {

    public static final String TABLENAME = "HPLUS_HEALTH_ACTIVITY_OVERLAY";

    /**
     * Properties of entity HPlusHealthActivityOverlay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TimestampFrom = new Property(0, int.class, "timestampFrom", true, "TIMESTAMP_FROM");
        public final static Property TimestampTo = new Property(1, int.class, "timestampTo", true, "TIMESTAMP_TO");
        public final static Property RawKind = new Property(2, int.class, "rawKind", true, "RAW_KIND");
        public final static Property DeviceId = new Property(3, long.class, "deviceId", true, "DEVICE_ID");
        public final static Property UserId = new Property(4, long.class, "userId", false, "USER_ID");
        public final static Property RawHPlusHealthData = new Property(5, byte[].class, "rawHPlusHealthData", false, "RAW_HPLUS_HEALTH_DATA");
    };

    private DaoSession daoSession;


    public HPlusHealthActivityOverlayDao(DaoConfig config) {
        super(config);
    }
    
    public HPlusHealthActivityOverlayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HPLUS_HEALTH_ACTIVITY_OVERLAY\" (" + //
                "\"TIMESTAMP_FROM\" INTEGER  NOT NULL ," + // 0: timestampFrom
                "\"TIMESTAMP_TO\" INTEGER  NOT NULL ," + // 1: timestampTo
                "\"RAW_KIND\" INTEGER  NOT NULL ," + // 2: rawKind
                "\"DEVICE_ID\" INTEGER  NOT NULL ," + // 3: deviceId
                "\"USER_ID\" INTEGER NOT NULL ," + // 4: userId
                "\"RAW_HPLUS_HEALTH_DATA\" BLOB," + // 5: rawHPlusHealthData
                "PRIMARY KEY (" +
                "\"TIMESTAMP_FROM\" ," +
                "\"TIMESTAMP_TO\" ," +
                "\"RAW_KIND\" ," +
                "\"DEVICE_ID\" ) ON CONFLICT REPLACE)" + ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) ? " WITHOUT ROWID;" : ";")
        );
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HPLUS_HEALTH_ACTIVITY_OVERLAY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HPlusHealthActivityOverlay entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimestampFrom());
        stmt.bindLong(2, entity.getTimestampTo());
        stmt.bindLong(3, entity.getRawKind());
        stmt.bindLong(4, entity.getDeviceId());
        stmt.bindLong(5, entity.getUserId());
 
        byte[] rawHPlusHealthData = entity.getRawHPlusHealthData();
        if (rawHPlusHealthData != null) {
            stmt.bindBlob(6, rawHPlusHealthData);
        }
    }

    @Override
    protected void attachEntity(HPlusHealthActivityOverlay entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public HPlusHealthActivityOverlay readEntity(Cursor cursor, int offset) {
        HPlusHealthActivityOverlay entity = new HPlusHealthActivityOverlay( //
            cursor.getInt(offset + 0), // timestampFrom
            cursor.getInt(offset + 1), // timestampTo
            cursor.getInt(offset + 2), // rawKind
            cursor.getLong(offset + 3), // deviceId
            cursor.getLong(offset + 4), // userId
            cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5) // rawHPlusHealthData
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HPlusHealthActivityOverlay entity, int offset) {
        entity.setTimestampFrom(cursor.getInt(offset + 0));
        entity.setTimestampTo(cursor.getInt(offset + 1));
        entity.setRawKind(cursor.getInt(offset + 2));
        entity.setDeviceId(cursor.getLong(offset + 3));
        entity.setUserId(cursor.getLong(offset + 4));
        entity.setRawHPlusHealthData(cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(HPlusHealthActivityOverlay entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(HPlusHealthActivityOverlay entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDeviceDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM HPLUS_HEALTH_ACTIVITY_OVERLAY T");
            builder.append(" LEFT JOIN DEVICE T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN USER T1 ON T.\"USER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected HPlusHealthActivityOverlay loadCurrentDeep(Cursor cursor, boolean lock) {
        HPlusHealthActivityOverlay entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Device device = loadCurrentOther(daoSession.getDeviceDao(), cursor, offset);
         if(device != null) {
            entity.setDevice(device);
        }
        offset += daoSession.getDeviceDao().getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }

        return entity;    
    }

    public HPlusHealthActivityOverlay loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<HPlusHealthActivityOverlay> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<HPlusHealthActivityOverlay> list = new ArrayList<HPlusHealthActivityOverlay>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<HPlusHealthActivityOverlay> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<HPlusHealthActivityOverlay> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
