package nodomain.freeyourgadget.gadgetbridge.entities;

import nodomain.freeyourgadget.gadgetbridge.entities.DaoSession;
import de.greenrobot.dao.DaoException;

import de.greenrobot.dao.AbstractDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PEBBLE_HEALTH_ACTIVITY_OVERLAY".
 */
public class PebbleHealthActivityOverlay {

    private int timestampFrom;
    private int timestampTo;
    private int rawKind;
    private long deviceId;
    private long userId;
    private byte[] rawPebbleHealthData;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PebbleHealthActivityOverlayDao myDao;

    private Device device;
    private Long device__resolvedKey;

    private User user;
    private Long user__resolvedKey;


    public PebbleHealthActivityOverlay() {
    }

    public PebbleHealthActivityOverlay(int timestampFrom, int timestampTo, int rawKind, long deviceId) {
        this.timestampFrom = timestampFrom;
        this.timestampTo = timestampTo;
        this.rawKind = rawKind;
        this.deviceId = deviceId;
    }

    public PebbleHealthActivityOverlay(int timestampFrom, int timestampTo, int rawKind, long deviceId, long userId, byte[] rawPebbleHealthData) {
        this.timestampFrom = timestampFrom;
        this.timestampTo = timestampTo;
        this.rawKind = rawKind;
        this.deviceId = deviceId;
        this.userId = userId;
        this.rawPebbleHealthData = rawPebbleHealthData;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPebbleHealthActivityOverlayDao() : null;
    }

    public int getTimestampFrom() {
        return timestampFrom;
    }

    public void setTimestampFrom(int timestampFrom) {
        this.timestampFrom = timestampFrom;
    }

    public int getTimestampTo() {
        return timestampTo;
    }

    public void setTimestampTo(int timestampTo) {
        this.timestampTo = timestampTo;
    }

    public int getRawKind() {
        return rawKind;
    }

    public void setRawKind(int rawKind) {
        this.rawKind = rawKind;
    }

    public long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(long deviceId) {
        this.deviceId = deviceId;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public byte[] getRawPebbleHealthData() {
        return rawPebbleHealthData;
    }

    public void setRawPebbleHealthData(byte[] rawPebbleHealthData) {
        this.rawPebbleHealthData = rawPebbleHealthData;
    }

    /** To-one relationship, resolved on first access. */
    public Device getDevice() {
        long __key = this.deviceId;
        if (device__resolvedKey == null || !device__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DeviceDao targetDao = daoSession.getDeviceDao();
            Device deviceNew = targetDao.load(__key);
            synchronized (this) {
                device = deviceNew;
            	device__resolvedKey = __key;
            }
        }
        return device;
    }

    public void setDevice(Device device) {
        if (device == null) {
            throw new DaoException("To-one property 'deviceId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.device = device;
            deviceId = device.getId();
            device__resolvedKey = deviceId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public User getUser() {
        long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        if (user == null) {
            throw new DaoException("To-one property 'userId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.user = user;
            userId = user.getId();
            user__resolvedKey = userId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
